cogs/events.py, cogs/faq.py, cogs/fun.py, cogs/leaderboards.py, cogs/modCommands.py, cogs/testCog.py, cogs/xp.py, data/constants.py, functions/database/stats.py, functions/reactWord.py, functions/timeFormatters.py
- `The Cooler Didier` no longer spams `Zandbak` `#error-logs` when sandboxing, and instead prints errors to your terminal.
- Fix `TimeFormatter` format string (`MM/DD` -> `DD/MM`)
- Remove useless field from `WhoIs`
- Make the `cog_check` from `TestCog` return `True` so it's useful for other people
- Add percentage to message counter & leaderboard
- Make `Memes` paginated - Fixes #14
- Make `FAQ` show the FAQ of the channel it's called in (in case it exists) - Fixes #19 
- Duplicate all letter emojis to open up more options for `React` - Fixes #20
=> Small updates

cogs/football.py, cogs/fun.py, cogs/modCommands.py, cogs/stats.py, cogs/tasks.py, cogs/translate.py, files/config.json, functions/database/memes.py, functions/football.py, functions/memes.py, functions/scraping.py
- Disable translate
- Rework Meme commands
- Rework Football commands
- Make Football usable by other people
- Fix sorting issue in channel activity
=> Small reworks

cogs/events.py, cogs/minesweeper.py, cogs/oneliners.py, cogs/reactword.py, cogs/school.py, databases.md, enums/courses.py, files/help.json, functions/football.py, functions/reactWord.py
``Pin`` command - fixes #23 
Add goal difference to ``jpl table`` - fixes #33 
Use message converter for ``react`` - fixes #9 
Resize ``minesweeper`` hard grid to prevent api limitations - fixes #17 
Make ``changelog`` command send github changelogs
Check ``react`` count before adding reactions - fixes #32
=> Close small issues

cogs/events.py, cogs/modCommands.py, data/database_classes/custom_commands.py, databases.md, files/help.json, functions/database/custom_commands.py
Fixes #55, also starts using Dataclasses (#57 )
=> Custom commands

cogs/events.py, data/regexes.py, data/snipe.py, tests/run_tests.py, tests/test_data/test_regexes.py
Don't snipe steam codes, fixes #78
(bot commands can be sniped, didn't do that)
Also wrote tests for this to get started on the painful journey of testing 6000 lines of code a year _after_ they've been written
=> Don't snipe steam codes + tests

tests/test_data/test_snipe.py
Thought about adding these extra tests on top of the previous ones I wrote in #79
=> Additional snipe tests

data/embeds/ufora.py, requirements.txt
Fix timestamp (i think, it's hard to test & datetime bad), unlimited length, FULL html-to-markdown support (eg. hyperlinks, file download links, ...), clean up some ugly stuff
Datetime & dateutil are both unable to parse the timezone so I hope it'll always be UTC+0
fixes #46 
fixes #44
=> Fixes for Ufora Notifications

cogs/school.py, data/schedule.py, files/schedules/31.json, functions/ufora_notifications.py, settings.py
=> Schedules minors, update Ufora id's

cogs/school.py, cogs/tasks.py, data/remind.py, data/schedule.py, files/schedules/31.json, settings.py
Customize reminder embed, customize embed in dm's
=> Les minors

cogs/school.py, cogs/slash/school_slash.py, data/embeds/food.py, functions/eten.py
fixes #94, add resto to embed, add date to embed
=> Menu Slash Command

files/config.json, files/schedules/32.json
=> 32 schedule

.github/workflows/python.yml, .pre-commit-config.yaml, pyproject.toml, readme.md
Add pre-commit hooks to avoid having to wait for workflows that can be checked beforehand. Code quality checks have been modified to require `tests` to complete before running, as they presumably have run before committing.
Mypy is not run as a hook here because it's too slow and it makes committing cumbersome.
=> Add pre-commit hooks

didier/cogs/school.py
Fixes #145 
The bug wasn't in the parsing but in the argument list.
=> Fix school date args

.flake8, didier/cogs/fun.py, didier/cogs/school.py, didier/data/apis/xkcd.py, didier/data/embeds/xkcd.py, didier/utils/discord/colours.py, run_db_scripts.py
- `xkcd` command
- `ufora` to link to a course's Ufora page
- The database script runner now correctly runs the mains of multiple scripts
- The school commands that took a `day` argument now correctly parse it - fixes #145
=> Didier v3.1

didier/data/embeds/ufora/announcements.py
Some Ufora announcements
Look
Like
This.
This PR aims to fix that.
=> Squash consecutive newlines

didier/didier.py
fixes #148 
Hybrid command errors work differently for some reason.
=> Update the error handler for hybrid commands

database/crud/deadlines.py, didier/cogs/school.py, didier/utils/discord/users.py
=> Filter out irrelevant deadlines

didier/cogs/owner.py
=> Add extra debug info to sync command

didier/didier.py
=> Make edit snipe keep the original message

.pre-commit-config.yaml, didier/data/embeds/deadlines.py, didier/utils/types/string.py, requirements-dev.txt
Fixed a bug where deadlines for elective master courses wouldn't be displayed.
Updated the `isort` pre-commit hook.
=> Fix bug in deadlines, update isort pre-commit hook

database/crud/events.py, didier/cogs/discord.py, didier/utils/timer.py, didier/utils/types/datetime.py, settings.py
=> Events QOL changes

database/scripts/db04_infosites.py
=> Add DB script to insert BSC and MSC infosites
